import 'product.dart';

final List<Product> products = [
  const Product(
    id: 1,
    name: "ShineStopper Sunnies",
    imagePath: "assets/images/shoe_img.png",
    price: 90,
    oldPrice: 100,
    discountLabel: "-10%",
  ),
  const Product(
    id: 1,
    name: "Shine Sunnies",
    imagePath: "assets\images\nvidia models, abdallh mostafa elrabiey.PNG",
    price: 90,
    oldPrice: 100,
    discountLabel: "-15%",
  ),
  const Product(
    id: 1,
    name: "Stopper Sunnies",
    imagePath: "assets/images/shoe_img.png",
    price: 90,
    oldPrice: 100,
    discountLabel: "-70%",
  ),
  const Product(
    id: 1,
    name: " Sunnies",
    imagePath: "assets/images/shoe_img.png",
    price: 90,
    oldPrice: 100,
    discountLabel: "-10%",
  ),
  const Product(
    id: 1,
    name: "ShineStopper ",
    imagePath: "assets\images\nvidia models, abdallh mostafa elrabiey.PNG",
    price: 90,
    oldPrice: 100,
    discountLabel: "-10%",
  ),
  const Product(
    id: 2,
    name: "Chucklesome Shoes",
    imagePath: "assets/images/home_card.png",
    price: 100,
  ),
  const Product(
    id: 3,
    name: "Purrfectly Wild",
    imagePath: "assets/images/shoe_img.png",
    price: 100,
  ),
  const Product(
    id: 4,
    name: "Brand Name Runner",
    imagePath: "assets/images/home_card.png",
    price: 100,
  ),
  const Product(
    id: 1,
    name: "ShineStopper Sunnies",
    imagePath: "assets/images/shoe_img.png",
    price: 90,
    oldPrice: 100,
    discountLabel: "-10%",
  ),
  const Product(
    id: 1,
    name: "ShineStopper Sunnies",
    imagePath: "assets/images/shoe_img.png",
    price: 90,
    oldPrice: 100,
    discountLabel: "-10%",
  ),
  const Product(
    id: 1,
    name: "ShineStopper Sunnies",
    imagePath: "assets/images/shoe_img.png",
    price: 90,
    oldPrice: 100,
    discountLabel: "-10%",
  ),
  const Product(
    id: 1,
    name: "ShineStopper Sunnies",
    imagePath: "assets/images/shoe_img.png",
    price: 90,
    oldPrice: 100,
    discountLabel: "-10%",
  ),
  const Product(
    id: 1,
    name: "ShineStopper Sunnies",
    imagePath: "assets/images/shoe_img.png",
    price: 90,
    oldPrice: 100,
    discountLabel: "-10%",
  ),
  const Product(
    id: 1,
    name: "ShineStopper Sunnies",
    imagePath: "assets/images/shoe_img.png",
    price: 90,
    oldPrice: 100,
    discountLabel: "-10%",
  ),
  const Product(
    id: 1,
    name: "ShineStopper Sunnies",
    imagePath: "assets/images/shoe_img.png",
    price: 90,
    oldPrice: 100,
    discountLabel: "-10%",
  ),
  const Product(
    id: 1,
    name: "ShineStopper Sunnies",
    imagePath: "assets/images/shoe_img.png",
    price: 90,
    oldPrice: 100,
    discountLabel: "-10%",
  ),
  const Product(
    id: 1,
    name: "ShineStopper Sunnies",
    imagePath: "assets/images/shoe_img.png",
    price: 90,
    oldPrice: 100,
    discountLabel: "-10%",
  ),
  const Product(
    id: 1,
    name: "ShineStopper Sunnies",
    imagePath: "assets/images/shoe_img.png",
    price: 90,
    oldPrice: 100,
    discountLabel: "-10%",
  ),
  const Product(
    id: 1,
    name: "ShineStopper Sunnies",
    imagePath: "assets/images/shoe_img.png",
    price: 90,
    oldPrice: 100,
    discountLabel: "-10%",
  ),
  const Product(
    id: 1,
    name: "ShineStopper Sunnies",
    imagePath: "assets/images/shoe_img.png",
    price: 90,
    oldPrice: 100,
    discountLabel: "-10%",
  ),
  

];
